redis:  
  fullnameOverride: redis
  usePassword: false
  replica:
    replicaCount: 0
  auth:
    enabled: false

appBackend:
  deployment:
    image: video-recognition_app-backend:local
    imagePullPolicy: Never
  ingress:
    ingressClassName: null
    useRegex: false
    pathType: "Prefix"
    path: "/"
  service:
    type: "LoadBalancer"
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

appFrontend:
  deployment:
    image: video-recognition_app-frontend:local
    imagePullPolicy: Never
  ingress:
    ingressClassName: null

frameExtractor:
  deployment:
    image: "video-recognition_frame-extractor:local"
    imagePullPolicy: Never

videoSplitter:
  deployment:
    image: "video-recognition_video-splitter:local"
    imagePullPolicy: Never

indexer:
  deployment:
    image: "video-recognition_indexer:local"
    imagePullPolicy: Never
