apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"    
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Release.Name }}-{{ .Release.Namespace }}-app-backend"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    nginx.org/websocket-services: "{{ .Release.Name }}-{{ .Release.Namespace }}-app-backend"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
    nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: "/api/(.*)"
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend
            port:
              number: 3000      
      - pathType: ImplementationSpecific
        path: "/app-sockets/socket/(.*)"
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend
            port:
              number: 3000