apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-frontend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app-frontend
  template:
    metadata:
      annotations:
        updateTimestamp: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app-frontend
    spec:
      containers:
      - name: app-frontend
        image: {{ .Values.appFronend.deployment.image }}
        imagePullPolicy: {{ .Values.appFronend.deployment.imagePullPolicy }}
        ports:
        - containerPort: 3005