apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"    
    nginx.ingress.kubernetes.io/websocket-services: "app-backend"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: "/api/(.*)"
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend
            port:
              number: 3000      
      - pathType: ImplementationSpecific
        path: "/app-sockets/sockets/(.*)"
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Release.Namespace }}-app-backend
            port:
              number: 3000                  