apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-downloader
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-downloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-downloader
    spec:
      containers:
      - name: downloader
        image: registry.digitalocean.com/devrel-registry/video-recognition_downloader      
        ports:
        - containerPort: 3001
        env:
        - name: KAFKA_BROKER
          value: kafka-service.dev.svc.cluster.local
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
