apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-indexer
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-indexer
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-indexer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-indexer
    spec:
      initContainers:
      - name: wait-for-redis
        image: goodsmileduck/redis-cli
        imagePullPolicy: IfNotPresent
        args: [ 'sh', '-c', 'until redis-cli -h redis-master -p 6379  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]
      containers:
      - name: indexer
        image: {{ .Values.indexer.deployment.image }}
        imagePullPolicy: {{ .Values.indexer.deployment.imagePullPolicy }}  
        ports:
        - containerPort: 3002
        # Consider adding in future
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "500m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        env:
        - name: IS_PROD
          value: "true"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  