apiVersion: v1
kind: Service
metadata:
  name: kafka-dev
  labels:
    app: kafka-dev
spec:
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-dev
spec:
  serviceName: kafka-dev
  replicas: 3
  selector:
    matchLabels:
      app: kafka-dev
  template:
    metadata:
      labels:
        app: kafka-dev
    spec:
      containers:
        - name: kafka-dev
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-dev:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          ports:
            - containerPort: 9092
