apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-indexer
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-indexer
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002